# Generated by Django 3.1 on 2020-08-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
