# Generated by Django 3.1 on 2020-09-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-timestamp']},
        ),
    ]
